### ISSUE TITLE
Search suggestions doesn't work with MultiZIM

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-lib#160] opened 2018-07-26 23:12 UTC
The old non full text search suggestions doesn't have any compatibility with multizim search. We could implement it on the Android side but it would be rather time consuming.

**Comment by kelson42** [comment] 2019-08-26 08:47
@mhutti1 Is that the bug which is blocking for multizim support in Kiwix-Android?

**Comment by mhutti1** [comment] 2019-08-26 08:52
Yes. All the things with this label are without significant hacky
workarounds.

**Comment by kelson42** [comment] 2021-05-02 04:11
Duplicate of #479. Keeping the newest one as we have a bit more comments.

**Closed by kelson42** 2021-05-02 04:11 UTC
Labels: kiwix-android-multizim, search
