### ISSUE TITLE
ctpp2 is no longer available

### ISSUE THREAD

**Issue by hashworks** [kiwix/kiwix-lib#189] opened 2018-12-17 10:41 UTC
The website (http://ctpp.havoc.ru/) referenced in the README file is no longer available.

**Comment by kelson42** [comment] 2018-12-17 16:47
Thank you for the feebdack. We are working anyway to replace ctpp2 by a better template engine. See #21. I will close this ticket as it basically is a duplicate of it.

**Closed by kelson42** 2018-12-17 16:48 UTC
Labels: bug, duplicate
